// TP5/react/src/pages/Register.jsx
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import Logo from "../components/Logo.tsx";
import {
    ArrowRightIcon,
    AtSymbolIcon,
    ExclamationCircleIcon,
    KeyIcon,
    UserIcon
} from '@heroicons/react/24/outline';

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL;

export default function Register({ handleLogin }) {
    const [name, setName] = useState('')
    const [login, setLogin] = useState('')
    const [password, setPassword] = useState('')
    const [errorMessage, setError] = useState('')
    const navigate = useNavigate()

    const handleSubmit = async (e) => {
        e.preventDefault()
        setError('')

        try {
            // Check if login exists
            const checkResponse = await fetch(`${API_BASE_URL}/users?login=${login}`)
            const existingUsers = await checkResponse.json()

            if (existingUsers.length > 0) {
                setError('Username already exists')
                return
            }

            // Create new user
            const newUser = { name, login, password }
            const response = await fetch(`${API_BASE_URL}/users`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(newUser)
            })

            const createdUser = await response.json()
            handleLogin(createdUser)
            navigate('/')
        } catch (err) {
            setError('Registration failed. Please try again.')
        }
    }

    return (
        <main className="flex items-center justify-center md:h-screen">
            <div className="relative mx-auto flex w-full max-w-[400px] flex-col space-y-2.5 p-4 md:-mt-32">
                <div className="flex h-20 w-full items-end rounded-lg bg-blue-500 p-3 md:h-36">
                    <div className="w-32 text-white md:w-36">
                        <Logo />
                    </div>
                </div>
                <form onSubmit={handleSubmit} className="space-y-3">
                    <div className="flex-1 rounded-lg bg-gray-50 px-6 pb-4 pt-8">
                        <h1 className="lusitana mb-3 text-2xl">
                            Create a new account
                        </h1>
                        <div className="w-full">
                            {/* Name Field */}
                            <div>
                                <label
                                    className="mb-3 mt-5 block text-xs font-medium text-gray-900"
                                    htmlFor="name"
                                >
                                    Full Name
                                </label>
                                <div className="relative">
                                    <input
                                        className="peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500"
                                        id="name"
                                        type="text"
                                        name="name"
                                        placeholder="Enter your full name"
                                        value={name}
                                        onChange={(e) => setName(e.target.value)}
                                        required
                                    />
                                    <UserIcon className="pointer-events-none absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900" />
                                </div>
                            </div>

                            {/* Login/Username Field */}
                            <div className="mt-4">
                                <label
                                    className="mb-3 mt-5 block text-xs font-medium text-gray-900"
                                    htmlFor="login"
                                >
                                    Username
                                </label>
                                <div className="relative">
                                    <input
                                        className="peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500"
                                        id="login"
                                        type="text"
                                        name="login"
                                        placeholder="Choose a username"
                                        value={login}
                                        onChange={(e) => setLogin(e.target.value)}
                                        required
                                    />
                                    <AtSymbolIcon className="pointer-events-none absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900" />
                                </div>
                            </div>

                            {/* Password Field */}
                            <div className="mt-4">
                                <label
                                    className="mb-3 mt-5 block text-xs font-medium text-gray-900"
                                    htmlFor="password"
                                >
                                    Password
                                </label>
                                <div className="relative">
                                    <input
                                        className="peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500"
                                        id="password"
                                        type="password"
                                        name="password"
                                        placeholder="Create a password"
                                        value={password}
                                        onChange={(e) => setPassword(e.target.value)}
                                        required
                                    />
                                    <KeyIcon className="pointer-events-none absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900" />
                                </div>
                            </div>
                        </div>

                        <button
                            type="submit"
                            className="flex h-10 items-center rounded-lg bg-blue-500 px-4 text-sm font-medium text-white transition-colors hover:bg-blue-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-500 active:bg-blue-600 aria-disabled:cursor-not-allowed aria-disabled:opacity-50 mt-4 w-full"
                        >
                            Sign Up <ArrowRightIcon className="ml-auto h-5 w-5 text-gray-50" />
                        </button>

                        <div
                            className="flex h-8 items-end space-x-1"
                            aria-live="polite"
                            aria-atomic="true"
                        >
                            {errorMessage && (
                                <>
                                    <ExclamationCircleIcon className="h-5 w-5 text-red-500" />
                                    <p className="text-sm text-red-500">{errorMessage}</p>
                                </>
                            )}
                        </div>

                        <div className="flex h-14 items-center justify-center underline text-gray-800">
                            <Link to="/login" className="text-sm">
                                Already have an account? Login here
                            </Link>
                        </div>
                    </div>
                </form>
            </div>
        </main>
    )
}

// TP5/angular/src/app/components/register/register.component.ts
import { Component } from '@angular/core';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import {UsersService} from "../../services/users.service";
import {Router} from "@angular/router";

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  registerForm: FormGroup;
  errorMessage: string = '';

  constructor(
    private fb: FormBuilder,
    private usersService: UsersService,
    private router: Router
  ) {
    this.registerForm = this.fb.group({
      login: ['', [Validators.required]],
      name: ['', [Validators.required]],
      password: ['', [Validators.required]],
    });
  }

  // Helper method to access form controls easily
  get f() {
    return this.registerForm.controls;
  }

  onSubmit(): void {
    this.errorMessage = '';
    if (this.registerForm.invalid) {
      this.errorMessage = 'Invalid login, name or password. Please try again.';
      return;
    }

    const { login, name, password } = this.registerForm.value;

    this.usersService.addUser({login, name, password}).subscribe({
      next: (res) => {
        if (res) {
          console.log("res", res);
          this.router.navigate(['/login']);
        } else {
          this.errorMessage = 'Invalid login or password. Please try again.';
        }
      },
      error: () => {
        this.errorMessage = 'An error occurred. Please try again later.';
      },
    });
  }
}

<main class="flex items-center justify-center md:h-screen">
  <div class="relative mx-auto flex w-full max-w-[400px] flex-col space-y-2.5 p-4 md:-mt-32">
    <div class="flex h-20 w-full items-end rounded-lg bg-blue-500 p-3 md:h-36">
      <div class="w-32 text-white md:w-36">
        <app-logo/>
      </div>
    </div>
    <form (ngSubmit)="onSubmit()" [formGroup]="registerForm" class="space-y-3">
      <div class="flex-1 rounded-lg bg-gray-50 px-6 pb-4 pt-8">
        <h1 class="Lusitana mb-3 text-2xl">
          Please register to continue.
        </h1>
        <div class="w-full">
          <div>
            <label
              class="mb-3 mt-5 block text-xs font-medium text-gray-900"
              for="login"
            >
              username
            </label>
            <div class="relative">
              <input
                class="peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500"
                id="login"
                type="text"
                name="login"
                placeholder="Enter your username"
                formControlName="login"
              />
              <i class="fa-solid fa-at pointer-events-none absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900"></i>
            </div>
          </div>
          <div class="mt-4">
            <label
              class="mb-3 mt-5 block text-xs font-medium text-gray-900"
              for="name"
            >
              name
            </label>
            <div class="relative">
              <input
                class="peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500"
                id="name"
                type="text"
                name="name"
                placeholder="Enter your name"
                formControlName="name"
              />
              <i class="fa-solid fa-at pointer-events-none absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900"></i>
            </div>
          </div>
          <div class="mt-4">
            <label
              class="mb-3 mt-5 block text-xs font-medium text-gray-900"
              for="password"
            >
              Password
            </label>
            <div class="relative">
              <input
                class="peer block w-full rounded-md border border-gray-200 py-[9px] pl-10 text-sm outline-2 placeholder:text-gray-500"
                id="password"
                type="password"
                name="password"
                placeholder="Enter password"
                formControlName="password"
              />
              <i class="fa-solid fa-key pointer-events-none absolute left-3 top-1/2 h-[18px] w-[18px] -translate-y-1/2 text-gray-500 peer-focus:text-gray-900" ></i>
            </div>
          </div>
        </div>
        <Button type="submit" class="flex h-10 items-center rounded-lg bg-blue-500 px-4 text-sm font-medium text-white transition-colors hover:bg-blue-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-500 active:bg-blue-600 aria-disabled:cursor-not-allowed aria-disabled:opacity-50 mt-4 w-full" >
          Register
          <i class="fa-solid fa-arrow-right ml-auto h-5 w-5 text-gray-50"></i>


        </Button>
        <div
          class="flex h-8 items-end space-x-1"
          aria-live="polite"
          aria-atomic="true"
          *ngIf="errorMessage !== ''"
        >
          <i class="h-5 w-5 text-red-500 fa-solid fa-circle-exclamation "></i>
          <p class="text-sm text-red-500">{{ errorMessage }}</p>
        </div>
        <div
          class="flex h-14 items-center justify-center underline text-gray-800"
        >
          <a routerLink="/login" class="text-sm">Already Registred ? Click to sign in </a>
        </div>
      </div>
    </form>

  </div>
</main>
{{this.registerForm.getRawValue() | json}}
